/*
  This file is automatically generated. Any changes will be overwritten.
  Modify kontakte.component.ts instead.
*/
import { LOCALE_ID, ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Subscription } from 'rxjs';

import { DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular/dist/dialog';
import { NotificationService } from '@radzen/angular/dist/notification';
import { ContentComponent } from '@radzen/angular/dist/content';
import { HeadingComponent } from '@radzen/angular/dist/heading';
import { ImageComponent } from '@radzen/angular/dist/image';
import { ButtonComponent } from '@radzen/angular/dist/button';
import { TabsComponent } from '@radzen/angular/dist/tabs';
import { PanelComponent } from '@radzen/angular/dist/panel';
import { TemplateFormComponent } from '@radzen/angular/dist/template-form';
import { LabelComponent } from '@radzen/angular/dist/label';
import { DropDownComponent } from '@radzen/angular/dist/dropdown';
import { RequiredValidatorComponent } from '@radzen/angular/dist/required-validator';
import { TextBoxComponent } from '@radzen/angular/dist/textbox';
import { TextAreaComponent } from '@radzen/angular/dist/textarea';
import { DatePickerComponent } from '@radzen/angular/dist/datepicker';
import { GridComponent } from '@radzen/angular/dist/grid';
import { UploadComponent } from '@radzen/angular/dist/upload';
import { HtmlComponent } from '@radzen/angular/dist/html';

import { ConfigService } from '../config.service';
import { MeldungOkComponent } from '../meldung-ok/meldung-ok.component';
import { NotizenEditorComponent } from '../notizen-editor/notizen-editor.component';
import { MeldungLoeschenComponent } from '../meldung-loeschen/meldung-loeschen.component';
import { EinstellungenInfotexteBearbeitenComponent } from '../einstellungen-infotexte-bearbeiten/einstellungen-infotexte-bearbeiten.component';
import { EinstellungenInfotexteNeuComponent } from '../einstellungen-infotexte-neu/einstellungen-infotexte-neu.component';
import { MeldungJaNeinComponent } from '../meldung-ja-nein/meldung-ja-nein.component';
import { KontakteKontaktpersonenBearbeitenComponent } from '../kontakte-kontaktpersonen-bearbeiten/kontakte-kontaktpersonen-bearbeiten.component';
import { KontakteKontaktpersonenNeuComponent } from '../kontakte-kontaktpersonen-neu/kontakte-kontaktpersonen-neu.component';
import { KontakteNeuComponent } from '../kontakte-neu/kontakte-neu.component';
import { KontakteSuchenComponent } from '../kontakte-suchen/kontakte-suchen.component';

import { DbOptimoService } from '../db-optimo.service';
import { SecurityService } from '../security.service';

export class KontakteGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild('content1') content1: ContentComponent;
  @ViewChild('heading8') heading8: HeadingComponent;
  @ViewChild('heading9') heading9: HeadingComponent;
  @ViewChild('image0') image0: ImageComponent;
  @ViewChild('heading2') heading2: HeadingComponent;
  @ViewChild('button0') button0: ButtonComponent;
  @ViewChild('buttonSuchenKontakte') buttonSuchenKontakte: ButtonComponent;
  @ViewChild('tabsKontakte') tabsKontakte: TabsComponent;
  @ViewChild('panel2') panel2: PanelComponent;
  @ViewChild('templateFormKontakte') templateFormKontakte: TemplateFormComponent;
  @ViewChild('label7') label7: LabelComponent;
  @ViewChild('anredeId') anredeId: DropDownComponent;
  @ViewChild('label8') label8: LabelComponent;
  @ViewChild('requiredValidator0') requiredValidator0: RequiredValidatorComponent;
  @ViewChild('name1') name1: TextBoxComponent;
  @ViewChild('label18') label18: LabelComponent;
  @ViewChild('requiredValidator2') requiredValidator2: RequiredValidatorComponent;
  @ViewChild('name2') name2: TextBoxComponent;
  @ViewChild('label9') label9: LabelComponent;
  @ViewChild('requiredValidator1') requiredValidator1: RequiredValidatorComponent;
  @ViewChild('nameKuerzel') nameKuerzel: TextBoxComponent;
  @ViewChild('label10') label10: LabelComponent;
  @ViewChild('titelVorne') titelVorne: TextBoxComponent;
  @ViewChild('label2') label2: LabelComponent;
  @ViewChild('titelHinten') titelHinten: TextBoxComponent;
  @ViewChild('label11') label11: LabelComponent;
  @ViewChild('strasse') strasse: TextBoxComponent;
  @ViewChild('label12') label12: LabelComponent;
  @ViewChild('plz') plz: TextBoxComponent;
  @ViewChild('label3') label3: LabelComponent;
  @ViewChild('ort') ort: TextBoxComponent;
  @ViewChild('label28') label28: LabelComponent;
  @ViewChild('notiz') notiz: TextAreaComponent;
  @ViewChild('label22') label22: LabelComponent;
  @ViewChild('geburtsdatum') geburtsdatum: DatePickerComponent;
  @ViewChild('label6') label6: LabelComponent;
  @ViewChild('versicherungsnummer') versicherungsnummer: TextBoxComponent;
  @ViewChild('label5') label5: LabelComponent;
  @ViewChild('staatsangehoerigkeit') staatsangehoerigkeit: TextBoxComponent;
  @ViewChild('label13') label13: LabelComponent;
  @ViewChild('telefon1') telefon1: TextBoxComponent;
  @ViewChild('label14') label14: LabelComponent;
  @ViewChild('telefon2') telefon2: TextBoxComponent;
  @ViewChild('label15') label15: LabelComponent;
  @ViewChild('eMail1') eMail1: TextBoxComponent;
  @ViewChild('label16') label16: LabelComponent;
  @ViewChild('eMail2') eMail2: TextBoxComponent;
  @ViewChild('label23') label23: LabelComponent;
  @ViewChild('webseite') webseite: TextBoxComponent;
  @ViewChild('label26') label26: LabelComponent;
  @ViewChild('label27') label27: LabelComponent;
  @ViewChild('kontoName') kontoName: TextBoxComponent;
  @ViewChild('label25') label25: LabelComponent;
  @ViewChild('kontoNummer') kontoNummer: TextBoxComponent;
  @ViewChild('label24') label24: LabelComponent;
  @ViewChild('kontoInfo') kontoInfo: TextAreaComponent;
  @ViewChild('button2') button2: ButtonComponent;
  @ViewChild('buttonKontakteSpeichern') buttonKontakteSpeichern: ButtonComponent;
  @ViewChild('button3') button3: ButtonComponent;
  @ViewChild('panel1') panel1: PanelComponent;
  @ViewChild('gridKontaktpersonen') gridKontaktpersonen: GridComponent;
  @ViewChild('buttonKontaktpersonNeu') buttonKontaktpersonNeu: ButtonComponent;
  @ViewChild('buttonKontaktpersonBearbeiten') buttonKontaktpersonBearbeiten: ButtonComponent;
  @ViewChild('buttonKontaktpersonLoeschen') buttonKontaktpersonLoeschen: ButtonComponent;
  @ViewChild('bild') bild: PanelComponent;
  @ViewChild('bildUrl') bildUrl: ImageComponent;
  @ViewChild('uploadBildBase') uploadBildBase: UploadComponent;
  @ViewChild('buttonBildEntfernen') buttonBildEntfernen: ButtonComponent;
  @ViewChild('panel4') panel4: PanelComponent;
  @ViewChild('gridNotizen') gridNotizen: GridComponent;
  @ViewChild('buttonNeueNotiz') buttonNeueNotiz: ButtonComponent;
  @ViewChild('buttonBearbeitenNotiz') buttonBearbeitenNotiz: ButtonComponent;
  @ViewChild('buttonLoeschenNotiz') buttonLoeschenNotiz: ButtonComponent;
  @ViewChild('panel6') panel6: PanelComponent;
  @ViewChild('htmlEditorInfotexte') htmlEditorInfotexte: HtmlComponent;
  @ViewChild('buttonKopieren') buttonKopieren: ButtonComponent;
  @ViewChild('buttonBearbeitenNotizEditor') buttonBearbeitenNotizEditor: ButtonComponent;
  @ViewChild('panel0') panel0: PanelComponent;
  @ViewChild('gridKontakte') gridKontakte: GridComponent;
  @ViewChild('buttonExport') buttonExport: ButtonComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  configService: ConfigService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  httpClient: HttpClient;

  locale: string;

  _location: Location;

  _subscription: Subscription;

  dbOptimo: DbOptimoService;

  security: SecurityService;
  bolLadenKontakte: any;
  tabsKontakteSelectedIndex: any;
  dsoBenutzer: any;
  rstBaseAnreden: any;
  dsoBaseKontakte: any;
  parameters: any;
  kontaktpersonenBaseID: any;
  dsoBaseKontaktpersonen: any;
  rstBaseKontaktpersonen: any;
  rstBaseKontaktpersonenCount: any;
  letzteInfotextID: any;
  letzteNotizID: any;
  rstNotizen: any;
  rstNotizenCount: any;
  strNotizHTML: any;
  dsoNotizen: any;
  rstBaseKontakte: any;
  rstBaseKontakteCount: any;
  dsoBaseKontakteAusListe: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.configService = this.injector.get(ConfigService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.locale = this.injector.get(LOCALE_ID);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.httpClient = this.injector.get(HttpClient);

    this.dbOptimo = this.injector.get(DbOptimoService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    if (this._subscription) {
      this._subscription.unsubscribe();
    }
  }


  load() {
    this.bolLadenKontakte = true;

    this.tabsKontakteSelectedIndex = 0;

    this.dbOptimo.getBenutzers(`BenutzerName eq '${this.security.user.name}'`, null, null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.dsoBenutzer = result.value[0];

      this.dbOptimo.getBaseAnredens(null, null, null, null, null, null, null, null)
      .subscribe((result: any) => {
        this.rstBaseAnreden = result.value;

        this.dbOptimo.getBaseByBaseId(null, this.dsoBenutzer.LetzteBaseID)
        .subscribe((result: any) => {
          this.dsoBaseKontakte = result;

          this.bolLadenKontakte = false;

          this.gridKontaktpersonen.load()

          this.gridNotizen.load();
        }, (result: any) => {
          this.notificationService.notify({ severity: "info", summary: ``, detail: `Klicke auf 'Suchen' um einen Kontakt auszuwählen!` });

          this.bolLadenKontakte = false;
        });
      }, (result: any) => {

      });
    }, (result: any) => {

    });

    this.gridKontakte.load();
  }

  button0Click(event: any) {
    this.dialogService.open(MeldungOkComponent, { parameters: {strMeldung: "Drucken ist für dieses Modul noch nicht aktiviert!"}, width: 600, title: `Info` });
  }

  buttonSuchenKontakteClick(event: any) {
    this.dialogService.open(KontakteSuchenComponent, { parameters: {}, width: 450, height: 700, title: `Suchen Kontakt` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.dsoBaseKontakte = result;
      }

      if (result != null) {
        this.gridKontaktpersonen.load()
      }

      if (result != null) {
        this.dsoBenutzer.LetzteBaseID = this.dsoBaseKontakte.BaseID
      }

      if (result != null) {
              this.dbOptimo.updateBenutzer(null, this.dsoBenutzer.BenutzerID, this.dsoBenutzer)
        .subscribe((result: any) => {
      
        }, (result: any) => {
      
        });
      }
    });
  }

  tabsKontakteChange(event: any) {
    this.tabsKontakteSelectedIndex = event.index;
  }

  button2Click(event: any) {
    this.dialogService.open(KontakteNeuComponent, { parameters: {}, width: 1000, title: `Neuer Kontakt` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.dsoBaseKontakte = result;
      }

      if (result != null) {
        this.gridKontaktpersonen.load()
      }

      if (result != null) {
        this.dsoBenutzer.LetzteBaseID = this.dsoBaseKontakte.BaseID
      }

      if (result != null) {
              this.dbOptimo.updateBenutzer(null, this.dsoBenutzer.BenutzerID, this.dsoBenutzer)
        .subscribe((result: any) => {
      
        }, (result: any) => {
      
        });
      }
    });
  }

  buttonKontakteSpeichernClick(event: any) {
    this.dbOptimo.updateBase(null, this.dsoBaseKontakte.BaseID, this.dsoBaseKontakte)
    .subscribe((result: any) => {
      this.notificationService.notify({ severity: "success", summary: ``, detail: `Änderungen gespeichert` });
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Änderungen konnten nicht gespeichert werden!` });
    });
  }

  button3Click(event: any) {
    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll der Kontakt '" + this.dsoBaseKontakte.Name1 + " " + this.dsoBaseKontakte.Name2 + "' gelöscht werden?"}, title: `Löschen Kontakt` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbOptimo.deleteBase(this.dsoBaseKontakte.BaseID)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontakt gelöscht` });

        this.dsoBaseKontakte = null;

        this.gridKontaktpersonen.load()

        this.notificationService.notify({ severity: "info", summary: ``, detail: `Klicke auf 'Suchen' um einen Kontakt auszuwählen!` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakt konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  gridKontaktpersonenLoadData(event: any) {
    this.kontaktpersonenBaseID = 0;

    if (this.dsoBaseKontakte != null) {
        this.kontaktpersonenBaseID = this.dsoBaseKontakte.BaseID;
    }

    this.dsoBaseKontaktpersonen = null;

    this.dbOptimo.getBaseKontaktes(`BaseID eq ${this.kontaktpersonenBaseID}`, event.top, event.skip, `${event.orderby || 'NameKontakt'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseKontaktpersonen = result.value;

      this.rstBaseKontaktpersonenCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontaktpersonen können nicht geladen werden!` });
    });
  }

  gridKontaktpersonenRowDoubleClick(event: any) {
    this.dialogService.open(KontakteKontaktpersonenBearbeitenComponent, { parameters: {KontaktID: event.KontaktID}, title: `Bearbeiten Kontaktperson` });
  }

  gridKontaktpersonenRowSelect(event: any) {
    this.dsoBaseKontaktpersonen = event;
  }

  buttonKontaktpersonNeuClick(event: any) {
    this.dialogService.open(KontakteKontaktpersonenNeuComponent, { parameters: {BaseID: this.dsoBaseKontakte.BaseID}, title: `Neue Kontaktperson` })
        .afterClosed().subscribe(result => {
              if (result != null) {
        this.gridKontaktpersonen.load();
      }
    });
  }

  buttonKontaktpersonBearbeitenClick(event: any) {
    this.dialogService.open(KontakteKontaktpersonenBearbeitenComponent, { parameters: {KontaktID: this.dsoBaseKontaktpersonen.KontaktID}, title: `Bearbeiten Kontaktperson` })
        .afterClosed().subscribe(result => {
              if (result != null) {
        this.gridKontaktpersonen.load();
      }
    });
  }

  buttonKontaktpersonLoeschenClick(event: any) {
    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll die Kontaktperson '" + this.dsoBaseKontaktpersonen.NameKontakt + "' gelöscht werden?"}, title: `Löschen Kontaktperson` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbOptimo.deleteBaseKontakte(this.dsoBaseKontaktpersonen.KontaktID)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Kontaktperson gelöscht` });

        this.gridKontaktpersonen.load();
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontaktperson konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  uploadBildBaseBeforeUpload(event: any) {
    var strDateiName = this.uploadBildBase.fileUpload.files[0].name;
var strDateiEndung = strDateiName.substring(strDateiName.indexOf("."));

this.dsoBaseKontakte.BildURL = 'https://medien.optimo.app/upload/bilder/base/KeinBildPerson.png';
this.dsoBaseKontakte.BildURL = 'https://medien.optimo.app/upload/bilder/base/' + this.dsoBaseKontakte.BaseID + strDateiEndung;
  }

  uploadBildBaseError(event: any) {
    this.notificationService.notify({ severity: "error", summary: `Bild`, detail: `Hochladen fehlgeschlagen!` });
  }

  uploadBildBaseUpload(event: any) {
    this.dbOptimo.updateBase(null, this.dsoBaseKontakte.BaseID, this.dsoBaseKontakte)
    .subscribe((result: any) => {

    }, (result: any) => {

    });

    this.notificationService.notify({ severity: "success", summary: `Bild`, detail: `Erfolgreich hochgeladen!` });
  }

  buttonBildEntfernenClick(event: any) {
    this.dialogService.open(MeldungJaNeinComponent, { parameters: {strMeldung: "Soll das Bild von '" + this.dsoBaseKontakte.Name1 + " " + this.dsoBaseKontakte.Name2 + "' entfernt werden?"}, title: `Bild entfernen` })
        .afterClosed().subscribe(result => {
              if (result == 'Ja') {
        this.dsoBaseKontakte.BildURL = 'https://medien.optimo.app/upload/bilder/base/KeinBildPerson.png';
      }

      if (result == 'Ja') {
              this.dbOptimo.updateBase(null, this.dsoBaseKontakte.BaseID, this.dsoBaseKontakte)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Bild entfernt` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Bild konnte nicht entfernt werden!` });
        });
      }
    });
  }

  gridNotizenLoadData(event: any) {
    this.dbOptimo.getNotizens(`LinkID eq ${this.dsoBaseKontakte.BaseID}`, event.top, event.skip, `${event.orderby || 'Titel'}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstNotizen = result.value;

      this.rstNotizenCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;

      if (this.rstNotizen.find(p => p.NotizID == this.letzteNotizID) != null) {
    // letzte...ID wurde in rst... gefunden
    this.gridNotizen.onSelect(this.rstNotizen.find(p => p.NotizID == this.letzteNotizID))
} else {
    // letzte...ID wurde in rst... NICHT gefunden
    this.letzteNotizID = null;
    this.gridNotizen.onSelect(this.rstNotizen[0]);
}
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Notizen konnten nicht geladen werden!` });
    });
  }

  gridNotizenRowDoubleClick(event: any) {
    this.letzteNotizID = this.dsoNotizen.NotizID;

    this.dialogService.open(EinstellungenInfotexteBearbeitenComponent, { parameters: {NotizID: this.dsoNotizen.NotizID}, title: `Bearbeiten Notiz` });
  }

  gridNotizenRowSelect(event: any) {
    this.strNotizHTML = event.Notit;

    this.dsoNotizen = event;
  }

  buttonNeueNotizClick(event: any) {
    this.letzteInfotextID = this.dsoNotizen.InfotextID;

    this.dialogService.open(EinstellungenInfotexteNeuComponent, { parameters: {}, title: `Neue Notiz ` })
        .afterClosed().subscribe(result => {
              if (result != null) {
            this.letzteNotizID = result.NotizID;
      }

      if (result != null) {
        this.gridNotizen.load();
      }
    });
  }

  buttonBearbeitenNotizClick(event: any) {
    this.letzteNotizID = this.dsoNotizen.NotizID;

    this.dialogService.open(EinstellungenInfotexteBearbeitenComponent, { parameters: {NotizID: this.dsoNotizen.NotizID}, title: `Bearbeiten Notiz` });
  }

  buttonLoeschenNotizClick(event: any) {
    this.letzteNotizID = null;

    this.dialogService.open(MeldungLoeschenComponent, { parameters: {strMeldung: "Soll die Notiz '" + this.dsoNotizen.Titel + "' gelöscht werden?"}, title: `Löschen Notiz` })
        .afterClosed().subscribe(result => {
              if (result == 'Löschen') {
              this.dbOptimo.deleteNotizen(this.dsoNotizen.NotizID)
        .subscribe((result: any) => {
              this.notificationService.notify({ severity: "success", summary: ``, detail: `Notiz gelöscht` });
        }, (result: any) => {
              this.notificationService.notify({ severity: "error", summary: ``, detail: `Notiz konnte nicht gelöscht werden!` });
        });
      }
    });
  }

  buttonKopierenClick(event: any) {
      // Create container for the HTML
  // [1]
  var container = document.createElement('div')
  container.innerHTML = this.strNotizHTML

  // Hide element
  // [2]
  container.style.position = 'fixed'
  container.style.pointerEvents = 'none'
  container.style.opacity = '0'
  container.style.background = 'white'

  // Mount the container to the DOM to make `contentWindow` available
  // [3]
  document.body.appendChild(container)

  // Copy to clipboard
  // [4]
  window.getSelection().removeAllRanges()

  var range = document.createRange()
  range.selectNode(container)
  window.getSelection().addRange(range)

  // [5]
  document.execCommand('copy')
  
  // Remove the container
  // [6]
  document.body.removeChild(container)

    this.notificationService.notify({ severity: "success", summary: ``, detail: `Text wurde kopiert` });
  }

  buttonBearbeitenNotizEditorClick(event: any) {
    this.letzteInfotextID = this.dsoNotizen.NotizID;

    this.dialogService.open(NotizenEditorComponent, { parameters: {NotizID: this.dsoNotizen.NotizID}, width: 720, title: `Bearbeiten` });
  }

  gridKontakteLoadData(event: any) {
    this.dbOptimo.getVwBaseKontaktes(`${event.filter}`, event.top, event.skip, `${event.orderby}`, event.top != null && event.skip != null, null, null, null)
    .subscribe((result: any) => {
      this.rstBaseKontakte = result.value;

      this.rstBaseKontakteCount = event.top != null && event.skip != null ? result['@odata.count'] : result.value.length;
    }, (result: any) => {
      this.notificationService.notify({ severity: "error", summary: ``, detail: `Kontakte können nicht geladen werden!` });
    });
  }

  gridKontakteRowDoubleClick(event: any) {
    this.tabsKontakteSelectedIndex = 0;

    this.dsoBaseKontakte = event;

    this.gridKontaktpersonen.load()

    this.dsoBenutzer.LetzteBaseID = this.dsoBaseKontakte.BaseID

    this.dbOptimo.updateBenutzer(null, this.dsoBenutzer.BenutzerID, this.dsoBenutzer)
    .subscribe((result: any) => {

    }, (result: any) => {

    });
  }

  gridKontakteRowSelect(event: any) {
    this.dsoBaseKontakteAusListe = event;
  }

  buttonExportClick(event: any) {
    this.dialogService.open(MeldungOkComponent, { parameters: {strMeldung: "Diese Funktion wurde noch nicht aktiviert!"}, title: `Export Kontakte` });
  }
}
